export const MovieActionTypes = {
  FETCH_MOVIES_UPCOMING_START: 'FETCH_MOVIES_UPCOMING_START',
  FETCH_MOVIES_UPCOMING_SUCCESS: 'FETCH_MOVIES_UPCOMING_SUCCESS',
  FETCH_MOVIES_UPCOMING_FAILURE: 'FETCH_MOVIES_UPCOMING_FAILURE',

  FETCH_MOVIES_POPULAR_START: 'FETCH_MOVIES_POPULAR_START',
  FETCH_MOVIES_POPULAR_SUCCESS: 'FETCH_MOVIES_POPULAR_SUCCESS',
  FETCH_MOVIES_POPULAR_FAILURE: 'FETCH_MOVIES_POPULAR_FAILURE',

  FETCH_MOVIES_NOWPLAYING_START: 'FETCH_MOVIES_NOWPLAYING_START',
  FETCH_MOVIES_NOWPLAYING_SUCCESS: 'FETCH_MOVIES_NOWPLAYING_SUCCESS',
  FETCH_MOVIES_NOWPLAYING_FAILURE: 'FETCH_MOVIES_NOWPLAYING_FAILURE',

  FETCH_MOVIES_TOPRATED_START: 'FETCH_MOVIES_TOPRATED_START',
  FETCH_MOVIES_TOPRATED_SUCCESS: 'FETCH_MOVIES_TOPRATED_SUCCESS',
  FETCH_MOVIES_TOPRATED_FAILURE: 'FETCH_MOVIES_TOPRATED_FAILURE',

  FETCH_MOVIES_GENRE_START: 'FETCH_MOVIES_GENRE_START',
  FETCH_MOVIES_GENRE_SUCCESS: 'FETCH_MOVIES_GENRE_SUCCESS',
  FETCH_MOVIES_GENRE_FAILURE: 'FETCH_MOVIES_GENRE_FAILURE',

  FETCH_MOVIE_DETAILS_START: 'FETCH_MOVIE_DETAILS_START',
  FETCH_MOVIE_DETAILS_SUCCESS: 'FETCH_MOVIE_DETAILS_SUCCESS',
  FETCH_MOVIE_DETAILS_FAILURE: 'FETCH_MOVIE_DETAILS_FAILURE',

  FETCH_MOVIE_CREDITS_START: 'FETCH_MOVIE_CREDITS_START',
  FETCH_MOVIE_CREDITS_SUCCESS: 'FETCH_MOVIE_CREDITS_SUCCESS',
  FETCH_MOVIE_CREDITS_FAILURE: 'FETCH_MOVIE_CREDITS_FAILURE',

  FETCH_MOVIE_TRAILERS_START: 'FETCH_MOVIE_TRAILERS_START',
  FETCH_MOVIE_TRAILERS_SUCCESS: 'FETCH_MOVIE_TRAILERS_SUCCESS',
  FETCH_MOVIE_TRAILERS_FAILURE: 'FETCH_MOVIE_TRAILERS_FAILURE',

  FETCH_MOVIE_REVIEWS_START: 'FETCH_MOVIE_REVIEWS_START',
  FETCH_MOVIE_REVIEWS_SUCCESS: 'FETCH_MOVIE_REVIEWS_SUCCESS',
  FETCH_MOVIE_REVIEWS_FAILURE: 'FETCH_MOVIE_REVIEWS_FAILURE',

  FETCH_MOVIES_TRENDING_START: 'FETCH_MOVIES_TRENDING_START',
  FETCH_MOVIES_TRENDING_SUCCESS: 'FETCH_MOVIES_TRENDING_SUCCESS',
  FETCH_MOVIES_TRENDING_FAILURE: 'FETCH_MOVIES_TRENDING_FAILURE',

  FETCH_MULTI_SEARCH_START: 'FETCH_MULTI_SEARCH_START',
  FETCH_MULTI_SEARCH_SUCCESS: 'FETCH_MULTI_SEARCH_SUCCESS',
  FETCH_MULTI_SEARCH_FAILURE: 'FETCH_MULTI_SEARCH_FAILURE',
};
