export const TVActionTypes = {
  FETCH_TV_AIRINGTODAY_START: 'FETCH_TV_AIRINGTODAY_START',
  FETCH_TV_AIRINGTODAY_SUCCESS: 'FETCH_TV_AIRINGTODAY_SUCCESS',
  FETCH_TV_AIRINGTODAY_FAILURE: 'FETCH_TV_AIRINGTODAY_FAILURE',

  FETCH_TV_POPULAR_START: 'FETCH_TV_POPULAR_START',
  FETCH_TV_POPULAR_SUCCESS: 'FETCH_TV_POPULAR_SUCCESS',
  FETCH_TV_POPULAR_FAILURE: 'FETCH_TV_POPULAR_FAILURE',

  FETCH_TV_ONTHEAIR_START: 'FETCH_TV_ONTHEAIR_START',
  FETCH_TV_ONTHEAIR_SUCCESS: 'FETCH_TV_ONTHEAIR_SUCCESS',
  FETCH_TV_ONTHEAIR_FAILURE: 'FETCH_TV_ONTHEAIR_FAILURE',

  FETCH_TV_TOPRATED_START: 'FETCH_TV_TOPRATED_START',
  FETCH_TV_TOPRATED_SUCCESS: 'FETCH_TV_TOPRATED_SUCCESS',
  FETCH_TV_TOPRATED_FAILURE: 'FETCH_TV_TOPRATED_FAILURE',
};
