export const MovieActionTypes = {
  FETCH_MOVIES_UPCOMING_START: 'FETCH_MOVIES_UPCOMING_START',
  FETCH_MOVIES_UPCOMING_SUCCESS: 'FETCH_MOVIES_UPCOMING_SUCCESS',
  FETCH_MOVIES_UPCOMING_FAILURE: 'FETCH_MOVIES_UPCOMING_FAILURE',

  FETCH_MOVIES_POPULAR_START: 'FETCH_MOVIES_POPULAR_START',
  FETCH_MOVIES_POPULAR_SUCCESS: 'FETCH_MOVIES_POPULAR_SUCCESS',
  FETCH_MOVIES_POPULAR_FAILURE: 'FETCH_MOVIES_POPULAR_FAILURE',

  FETCH_MOVIES_NOWPLAYING_START: 'FETCH_MOVIES_NOWPLAYING_START',
  FETCH_MOVIES_NOWPLAYING_SUCCESS: 'FETCH_MOVIES_NOWPLAYING_SUCCESS',
  FETCH_MOVIES_NOWPLAYING_FAILURE: 'FETCH_MOVIES_NOWPLAYING_FAILURE',

  FETCH_MOVIES_TOPRATED_START: 'FETCH_MOVIES_TOPRATED_START',
  FETCH_MOVIES_TOPRATED_SUCCESS: 'FETCH_MOVIES_TOPRATED_SUCCESS',
  FETCH_MOVIES_TOPRATED_FAILURE: 'FETCH_MOVIES_TOPRATED_FAILURE',
};
