export const MovieActionTypes = {
  FETCH_MOVIES_UPCOMING_START: 'FETCH_MOVIES_UPCOMING_START',
  FETCH_MOVIES_UPCOMING_SUCCESS: 'FETCH_MOVIES_UPCOMING_SUCCESS',
  FETCH_MOVIES_UPCOMING_FAILURE: 'FETCH_MOVIES_UPCOMING_FAILURE',
};
