export const UserActionTypes = {
  SET_ITEM_TYPE: 'SET_ITEM_TYPE',

  SET_CURRENT_USER: 'SET_CURRENT_USER',

  CHECK_USER_SESSION: 'CHECK_USER_SESSION',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  POST_USER_WATCHED_START: 'POST_USER_WATCHED_START',
  POST_USER_WATCHED_SUCCESS: 'POST_USER_WATCHED_SUCCESS',
  POST_USER_WATCHED_FAILURE: 'POST_USER_WATCHED_FAILURE',

  GET_USER_WATCHED_START: 'GET_USER_WATCHED_START',
  GET_USER_WATCHED_SUCCESS: 'GET_USER_WATCHED_SUCCESS',
  GET_USER_WATCHED_FAILURE: 'GET_USER_WATCHED_FAILURE',

  DELETE_USER_WATCHED_START: 'DELETE_USER_WATCHED_START',
  DELETE_USER_WATCHED_SUCCESS: 'DELETE_USER_WATCHED_SUCCESS',
  DELETE_USER_WATCHED_FAILURE: 'DELETE_USER_WATCHED_FAILURE',
};
